<?php

namespace Database\Seeders;

use App\Models\Kanji;
use App\Models\User;
use Illuminate\Database\Seeder;

class KanjiSampleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sensei = User::role('sensei')->first();
        $senseiId = $sensei?->id;

        $kanjiData = [
            [
                'kanji' => '日',
                'hiragana' => 'ひ / にち',
                'meaning_id' => 'Matahari / Hari',
                'romaji' => 'hi / nichi',
                'onyomi' => 'ニチ, ジツ',
                'kunyomi' => 'ひ, -び, -か',
                'level' => 'N5',
                'stroke_count' => 4,
                'notes' => 'Contoh: 日本 (Nihon / Jepang), 日曜日 (Nichiyoubi / Minggu)',
            ],
            [
                'kanji' => '月',
                'hiragana' => 'つき / げつ',
                'meaning_id' => 'Bulan',
                'romaji' => 'tsuki / getsu',
                'onyomi' => 'ゲツ, ガツ',
                'kunyomi' => 'つき',
                'level' => 'N5',
                'stroke_count' => 4,
                'notes' => 'Contoh: 月曜日 (Getsuyoubi / Senin), 一月 (Ichigatsu / Januari)',
            ],
            [
                'kanji' => '火',
                'hiragana' => 'ひ / か',
                'meaning_id' => 'Api',
                'romaji' => 'hi / ka',
                'onyomi' => 'カ',
                'kunyomi' => 'ひ, -び, ほ-',
                'level' => 'N5',
                'stroke_count' => 4,
                'notes' => 'Contoh: 火曜日 (Kayoubi / Selasa), 花火 (Hanabi / Kembang api)',
            ],
            [
                'kanji' => '水',
                'hiragana' => 'みず / すい',
                'meaning_id' => 'Air',
                'romaji' => 'mizu / sui',
                'onyomi' => 'スイ',
                'kunyomi' => 'みず',
                'level' => 'N5',
                'stroke_count' => 4,
                'notes' => 'Contoh: 水曜日 (Suiyoubi / Rabu), お水 (Omizu / Air minum)',
            ],
            [
                'kanji' => '木',
                'hiragana' => 'き / もく',
                'meaning_id' => 'Pohon / Kayu',
                'romaji' => 'ki / moku',
                'onyomi' => 'ボク, モク',
                'kunyomi' => 'き, こ-',
                'level' => 'N5',
                'stroke_count' => 4,
                'notes' => 'Contoh: 木曜日 (Mokuyoubi / Kamis)',
            ],
            [
                'kanji' => '金',
                'hiragana' => 'かね / きん',
                'meaning_id' => 'Uang / Emas',
                'romaji' => 'kane / kin',
                'onyomi' => 'キン, コン',
                'kunyomi' => 'かね, かな-',
                'level' => 'N5',
                'stroke_count' => 8,
                'notes' => 'Contoh: 金曜日 (Kinyoubi / Jumat), お金 (Okane / Uang)',
            ],
            [
                'kanji' => '土',
                'hiragana' => 'つち / ど',
                'meaning_id' => 'Tanah',
                'romaji' => 'tsuchi / do',
                'onyomi' => 'ド, ト',
                'kunyomi' => 'つち',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 土曜日 (Doyoubi / Sabtu), 土地 (Tochi / Tanah/Lahan)',
            ],
            [
                'kanji' => '山',
                'hiragana' => 'やま / さん',
                'meaning_id' => 'Gunung',
                'romaji' => 'yama / san',
                'onyomi' => 'サン, セン',
                'kunyomi' => 'やま',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 富士山 (Fujisan / Gunung Fuji)',
            ],
            [
                'kanji' => '川',
                'hiragana' => 'かわ / がわ',
                'meaning_id' => 'Sungai',
                'romaji' => 'kawa / gawa',
                'onyomi' => 'セン',
                'kunyomi' => 'かわ',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: ナイル川 (Nairu-gawa / Sungai Nil)',
            ],
            [
                'kanji' => '人',
                'hiragana' => 'ひと / じん / にん',
                'meaning_id' => 'Orang / Manusia',
                'romaji' => 'hito / jin / nin',
                'onyomi' => 'ジン, ニン',
                'kunyomi' => 'ひと',
                'level' => 'N5',
                'stroke_count' => 2,
                'notes' => 'Contoh: 日本人 (Nihonjin / Orang Jepang), 三人 (Sannin / Tiga orang)',
            ],
            [
                'kanji' => '子',
                'hiragana' => 'こ / し',
                'meaning_id' => 'Anak',
                'romaji' => 'ko / shi',
                'onyomi' => 'シ, ス',
                'kunyomi' => 'こ',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 子供 (Kodomo / Anak-anak)',
            ],
            [
                'kanji' => '女',
                'hiragana' => 'おんな / じょ',
                'meaning_id' => 'Wanita / Perempuan',
                'romaji' => 'onna / jo',
                'onyomi' => 'ジョ, ニョ',
                'kunyomi' => 'おんな, め',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 女の子 (Onna no ko / Anak perempuan)',
            ],
            [
                'kanji' => '男',
                'hiragana' => 'おとこ / だん',
                'meaning_id' => 'Pria / Laki-laki',
                'romaji' => 'otoko / dan',
                'onyomi' => 'ダン, ナン',
                'kunyomi' => 'おとこ',
                'level' => 'N5',
                'stroke_count' => 7,
                'notes' => 'Contoh: 男の子 (Otoko no ko / Anak laki-laki), 男の人 (Otoko no hito / Pria)',
            ],
            [
                'kanji' => '学',
                'hiragana' => 'まな・ぶ / がく',
                'meaning_id' => 'Belajar / Studi',
                'romaji' => 'mana-bu / gaku',
                'onyomi' => 'ガク',
                'kunyomi' => 'まな・ぶ',
                'level' => 'N5',
                'stroke_count' => 8,
                'notes' => 'Contoh: 学生 (Gakusei / Murid/Siswa), 学校 (Gakkou / Sekolah)',
            ],
            [
                'kanji' => '校',
                'hiragana' => 'こう',
                'meaning_id' => 'Sekolah',
                'romaji' => 'kou',
                'onyomi' => 'コウ',
                'kunyomi' => '',
                'level' => 'N5',
                'stroke_count' => 10,
                'notes' => 'Contoh: 高校 (Koukou / SMA), 中学校 (Chuugakkou / SMP)',
            ],
            [
                'kanji' => '先',
                'hiragana' => 'さき / せん',
                'meaning_id' => 'Sebelum / Lebih dulu',
                'romaji' => 'saki / sen',
                'onyomi' => 'セン',
                'kunyomi' => 'さき',
                'level' => 'N5',
                'stroke_count' => 6,
                'notes' => 'Contoh: 先生 (Sensei / Guru), 先週 (Senshuu / Minggu lalu)',
            ],
            [
                'kanji' => '生',
                'hiragana' => 'い・きる / う・まれる / せい',
                'meaning_id' => 'Hidup / Lahir',
                'romaji' => 'i-kiru / sei',
                'onyomi' => 'セイ, ショウ',
                'kunyomi' => 'い・きる, う・まれる, なま',
                'level' => 'N5',
                'stroke_count' => 5,
                'notes' => 'Contoh: 誕生日 (Tanjoubi / Hari ulang tahun), 生徒 (Seito / Murid)',
            ],
            [
                'kanji' => '食',
                'hiragana' => 'た・べる / しょく',
                'meaning_id' => 'Makan / Makanan',
                'romaji' => 'ta-beru / shoku',
                'onyomi' => 'ショク, ジキ',
                'kunyomi' => 'た・べる, く・う',
                'level' => 'N5',
                'stroke_count' => 9,
                'notes' => 'Contoh: 食べ物 (Tabemono / Makanan), 食事 (Shokuji / Makan bersama)',
            ],
            [
                'kanji' => '飲',
                'hiragana' => 'の・む / いん',
                'meaning_id' => 'Minum',
                'romaji' => 'no-mu / in',
                'onyomi' => 'イン',
                'kunyomi' => 'の・む',
                'level' => 'N5',
                'stroke_count' => 12,
                'notes' => 'Contoh: 飲み物 (Nomimono / Minuman)',
            ],
            [
                'kanji' => '見',
                'hiragana' => 'み・る / けん',
                'meaning_id' => 'Melihat',
                'romaji' => 'mi-ru / ken',
                'onyomi' => 'ケン',
                'kunyomi' => 'み・る, み・える, み・せる',
                'level' => 'N5',
                'stroke_count' => 7,
                'notes' => 'Contoh: 意見 (Iken / Pendapat), 見学 (Kengaku / Kunjungan studi)',
            ],
            [
                'kanji' => '行',
                'hiragana' => 'い・く / おこな・う / こう',
                'meaning_id' => 'Pergi / Melakukan',
                'romaji' => 'i-ku / kou',
                'onyomi' => 'コウ, ギョウ',
                'kunyomi' => 'い・く, ゆ・く, おこな・う',
                'level' => 'N5',
                'stroke_count' => 6,
                'notes' => 'Contoh: 銀行 (Ginkou / Bank), 旅行 (Ryokou / Liburan/Wisata)',
            ],
            [
                'kanji' => '来',
                'hiragana' => 'く・る / らい',
                'meaning_id' => 'Datang',
                'romaji' => 'ku-ru / rai',
                'onyomi' => 'ライ',
                'kunyomi' => 'く・る, きた・る',
                'level' => 'N5',
                'stroke_count' => 7,
                'notes' => 'Contoh: 来週 (Raishuu / Minggu depan), 来年 (Rainen / Tahun depan)',
            ],
            [
                'kanji' => '本',
                'hiragana' => 'ほん / もと',
                'meaning_id' => 'Buku / Asal / Dasar',
                'romaji' => 'hon / moto',
                'onyomi' => 'ホン',
                'kunyomi' => 'もと',
                'level' => 'N5',
                'stroke_count' => 5,
                'notes' => 'Contoh: 日本 (Nihon / Jepang), 本屋 (Hon\'ya / Toko buku)',
            ],
            [
                'kanji' => '大',
                'hiragana' => 'おお・きい / だい / たい',
                'meaning_id' => 'Besar',
                'romaji' => 'oo-kii / dai',
                'onyomi' => 'ダイ, タイ',
                'kunyomi' => 'おお・きい',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 大学 (Daigaku / Universitas), 大切 (Taisetsu / Berharga/Penting)',
            ],
            [
                'kanji' => '小',
                'hiragana' => 'ちい・さい / しょう',
                'meaning_id' => 'Kecil',
                'romaji' => 'chii-sai / shou',
                'onyomi' => 'ショウ',
                'kunyomi' => 'ちい・さい, こ-, お-',
                'level' => 'N5',
                'stroke_count' => 3,
                'notes' => 'Contoh: 小学校 (Shougakkou / SD), 小鳥 (Kotori / Burung kecil)',
            ],
        ];

        foreach ($kanjiData as $data) {
            Kanji::firstOrCreate(
                ['kanji' => $data['kanji']],
                array_merge($data, ['created_by' => $senseiId])
            );
        }
    }
}
